# Export some variable found by CMake


PARFLOW_VERSION_STRING="v3.3.1-IGE-329-g414107a2"
PARFLOW_VERSION="3.3.1"
PARFLOW_VERSION_MAJOR=3
PARFLOW_VERSION_MINOR=3
PARFLOW_VERSION_PATCH=1
PARFLOW_VERSION_HASH="414107a2"
PARFLOW_VERSION_EXTRA="IGE"

MPIEXEC="/home/hectorb/PARFLOW/SOURCES/PF_2022_07/openmpi-5.0.7/bin/mpiexec"
MPIEXEC_NUMPROC_FLAG="-n"
MPIEXEC_POSTFLAGS=""
MPIEXEC_PREFLAGS=""
